### ISSUE TITLE
Small changes are required in app to add "gendt" field

### ISSUE THREAD

**Issue by satisharalkar** [aerele/reconciler#17]
Hi Team,

Thanks a lot for your efforts to make this app. We installed app and observed that small changes we have to make to json file to upload it successfully. 

Field "gendt" was added in json file as shown in attachment. 

Traceback (most recent call last):
  File "apps/reconciler/reconciler/reconciler/doctype/cd_gstr_2b_data_upload_tool/cd_gstr_2b_data_upload_tool.py", line 87, in create_gstr2b_entries
    data['cf_generation_date']  = datetime.strptime(json_data['data']['gendt'] , "%d-%m-%Y").date()
KeyError: 'gendt'

![image](https://user-images.githubusercontent.com/17386166/177041498-a01c9081-33ba-404b-855e-01bed50d030c.png)

![image](https://user-images.githubusercontent.com/17386166/177096993-0cf13963-eb78-49e9-a64f-58725bcd3320.png)

Regards,
Satish Aralkar

**Comment by karthikeyan5** [comment]
@satisharalkar, are you downloading 2B or 2A? because 2B report JSON already has the "gendt" in it. We have multiple companies that upload the 2B JSON as it is from the GST Portal.

Closing this as this app only supports 2B as of now.
